# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 26, 16, 11, 54, 112719, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 26, 16, 11, 57, 448763, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('Management', 'Management'), ('PR Department', 'PR Department'), ('Dev Department', 'Dev Department'), ('UX Department', 'UX Department'), ('Law Department', 'Law Department'), ('Farmer VR Department', 'Farmer VR Department'), ('UI Department', 'UI Department'), ('Other', 'Other')], max_length=200, null=True, verbose_name='Department'),
        ),
    ]
