# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20160526_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 26, 16, 11, 23, 409358, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 26, 16, 11, 26, 985451, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
