# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Sent'), (2, 'Approved')], default=0)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_modified', models.DateTimeField(auto_now=True)),
                ('source_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_source', to='company.Company')),
                ('target_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_target', to='company.Company')),
            ],
            options={
                'verbose_name': 'Friend Request',
                'verbose_name_plural': 'Friend Requests',
            },
        ),
    ]
