# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_friendcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendcompany',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Sent'), (2, 'Approved'), (3, 'Cancelled')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='friendcompany',
            unique_together=set([('source_company', 'target_company')]),
        ),
    ]
